export enum categoryType {
  OperatingSystem = 'Operating System',
  ApplicationSoftware = 'Application Software',
  HardwareComponent = 'Hardware Component',
  MobileAccessory = 'Mobile Accessory',
  ComputerAccessory = 'Computer Accessory',
  PeripheralDevice = 'Peripheral Device',
  DisplayDevice = 'Display Device',
  PaidSoftware = 'Paid Software',
  DigitalLicense = 'Digital License',
  StorageDevice = 'Storage Device',
  NetworkingDevice = 'Networking Device',
  GamingDevice = 'Gaming Device',
  CoolingSolution = 'Cooling Solution',
  PowerSupply = 'Power Supply',
  InputDevice = 'Input Device',
  SmartHomeDevice = 'Smart Home Device',
  Smartphone = 'Smartphone',
  Tablet = 'Tablet',
  WearableDevice = 'Wearable Device',
  VirtualReality = 'Virtual Reality',
  AugmentedReality = 'Augmented Reality',
  AntivirusSoftware = 'Antivirus Software',
  GraphicsCard = 'Graphics Card',
  Processor = 'Processor',
  Motherboard = 'Motherboard',
  RAM = 'RAM',
  ExternalStorage = 'External Storage',
  BatteryBackup = 'Battery Backup',
  Cable = 'Cable',
  GamingChair = 'Gaming Chair',
  Printer = 'Printer',
  Keyboard = 'Keyboard',
  Mouse = 'Mouse',
  Speaker = 'Speaker',
  Headphones = 'Headphones',
  Monitor = 'Monitor',
  Laptop = 'Laptop',
  Headset='Headset'
}

export enum platformType {
  Windows = 'Windows',
  Mac = 'Mac',
  Linux = 'Linux',
  Android = 'Android',
  IOS = 'iOS',
  CrossPlatform = 'Cross Platform',
  PlayStation = 'PlayStation',
  Xbox = 'Xbox',
  SmartTV = 'Smart TV',
  WebBased = 'Web Based',
  IoT = 'IoT',
  Cloud = 'Cloud',
  ChromeOS = 'ChromeOS',
  Unix = 'Unix',
  VRPlatform = 'VR Platform',
  ARPlatform = 'AR Platform',
  Universal = 'Universal',
  None='None'
}

export enum baseType {
  Computer = 'Computer',
  Mobile = 'Mobile',
  Tablet = 'Tablet',
  Wearable = 'Wearable',
  Peripheral = 'Peripheral',
  Software = 'Software',
  GamingConsole = 'Gaming Console',
  Accessory = 'Accessory',
  Networking = 'Networking',
  SmartHome = 'Smart Home',
  Storage = 'Storage',
  Cooling = 'Cooling',
  Display = 'Display',
  Audio = 'Audio',
  VirtualReality = 'Virtual Reality',
  AugmentedReality = 'Augmented Reality',
  Security = 'Security',
  Battery = 'Battery',
  IoTDevice = 'IoT Device',
  CloudService = 'Cloud Service',
  Furniture = 'Furniture',
  None='None'
}